apiVersion: v1
kind: Service
metadata:
  name: consul-svc
  labels:
    app: consul-app
spec:
  ports:
  - port: 8500
    targetPort: 8500
  selector:
    app: consul-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-deployment
  labels:
    app: consul-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-app
  template:
    metadata:
      labels:
        app: consul-app
    spec:
      containers:
      - name: consul
        image: consul
        ports:
        - containerPort: 8500
        imagePullPolicy: Always