apiVersion: v1
kind: Service
metadata:
  name: api-gw-svc
  labels:
    app: api-gw-app
spec: 
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9000
  selector:
    app: api-gw-app
---
apiVersion: v1
kind: Service
metadata:
  name: api-cat-svc
  labels:
    app: api-cat-app
spec: 
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: api-cat-app
---
apiVersion: v1
kind: Service
metadata:
  name: api-emp-svc
  labels:
    app: api-emp-app
spec: 
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: api-emp-app